// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ads/adClick': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ads/adClick').default>>>>
    }
    '/api/ads/itemAdClick': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ads/itemAdClick').default>>>>
    }
    '/api/ads/position': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ads/position').default>>>>
    }
    '/api/anime/collect': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/anime/collect').default>>>>
    }
    '/api/anime/detail': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/anime/detail').default>>>>
    }
    '/api/anime/like': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/anime/like').default>>>>
    }
    '/api/anime/select': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/anime/select').default>>>>
    }
    '/api/app/firstVisitInApp': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/app/firstVisitInApp').default>>>>
    }
    '/api/app/pwa': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/app/pwa').default>>>>
    }
    '/api/article/collect': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/article/collect').default>>>>
    }
    '/api/article/comment': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/article/comment').default>>>>
    }
    '/api/article/comments': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/article/comments').default>>>>
    }
    '/api/article/detail': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/article/detail').default>>>>
    }
    '/api/article/like': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/article/like').default>>>>
    }
    '/api/article/select': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/article/select').default>>>>
    }
    '/api/auth/change-password': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/change-password').default>>>>
    }
    '/api/auth/forgot-password': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/forgot-password').default>>>>
    }
    '/api/auth/login': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login').default>>>>
    }
    '/api/auth/prepare-register': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/prepare-register').default>>>>
    }
    '/api/auth/refreshToken': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/refreshToken').default>>>>
    }
    '/api/auth/register': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register').default>>>>
    }
    '/api/auth/set-password': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/set-password').default>>>>
    }
    '/api/config': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/config/index').default>>>>
    }
    '/api/explore/activeVisitor': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/explore/activeVisitor').default>>>>
    }
    '/api/explore/collect': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/explore/collect').default>>>>
    }
    '/api/explore/comment': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/explore/comment').default>>>>
    }
    '/api/explore/comments': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/explore/comments').default>>>>
    }
    '/api/explore/detail': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/explore/detail').default>>>>
    }
    '/api/explore/feed': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/explore/feed').default>>>>
    }
    '/api/explore/follow': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/explore/follow').default>>>>
    }
    '/api/explore/like': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/explore/like').default>>>>
    }
    '/api/explore/newVisitor': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/explore/newVisitor').default>>>>
    }
    '/api/member': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/member/index').default>>>>
    }
    '/api/member/refresh-token': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/member/refresh-token').default>>>>
    }
    '/api/pageinfo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pageinfo/index').default>>>>
    }
    '/api/user/change-password': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/change-password').default>>>>
    }
    '/api/user': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/index').default>>>>
    }
    '/api/user/like-feed': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/like-feed').default>>>>
    }
    '/api/user/send-email-code': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/send-email-code').default>>>>
    }
    '/api/user/set-user-info': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/set-user-info').default>>>>
    }
    '/api/user/star-feed': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/star-feed').default>>>>
    }
    '/api/user/user-feed': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/user-feed').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}